apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - scheduler.yaml
images:
  - name: ghcr.io/kvaster/topols
    newName: registry.kvaster.com/topols
    newTag: 0.7.1
configMapGenerator:
  - name: scheduler-options
    namespace: topols-system
    files:
      - scheduler-options.yaml
