apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: topols-system
  name: topols-scheduler
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: topols-scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: topols-scheduler
    spec:
      securityContext:
        runAsUser:  10000
        runAsGroup: 10000
      serviceAccountName: topols-scheduler
      containers:
        - name: topols-scheduler
          image: quay.io/topols/topols:latest
          command:
            - /topols-scheduler
            - --config=/etc/topols/scheduler-options.yaml
          livenessProbe:
            httpGet:
              host: localhost
              port: 9251
              path: /status
          volumeMounts:
            - mountPath: /etc/topols
              name: scheduler-options
      hostNetwork: true
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      volumes:
        - name: scheduler-options
          configMap:
            name: scheduler-options
