apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: topols-hook
  annotations:
    cert-manager.io/inject-ca-from: topols-system/mutatingwebhook
  labels:
    app.kubernetes.io/name: topols-hook
webhooks:
  - name: pod-hook.topols.kvaster.com
    namespaceSelector:
      matchExpressions:
      - key: topols.kvaster.com/webhook
        operator: NotIn
        values: ["ignore"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: topols-system
        name: controller
        path: /pod/mutate
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
  - name: pvc-hook.topols.kvaster.com
    namespaceSelector:
      matchExpressions:
      - key: topols.kvaster.com/webhook
        operator: NotIn
        values: ["ignore"]
    failurePolicy: Fail
    clientConfig:
      service:
        namespace: topols-system
        name: controller
        path: /pvc/mutate
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["persistentvolumeclaims"]
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None

