apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: topols-system
  name: node
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: topols-system:node
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["topols.kvaster.com"]
    resources: ["logicalvolumes", "logicalvolumes/status"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csidrivers"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: ["topols-node"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: topols-system:node
subjects:
  - kind: ServiceAccount
    name: node
    namespace: topols-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: topols-system:node

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: topols-system
  name: node
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: node
  template:
    metadata:
      labels:
        app.kubernetes.io/name: node
      annotations:
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: node
      containers:
        - name: topols-node
          image: quay.io/topols/topols:latest
          securityContext:
            privileged: true
            capabilities:
              add: ["SYS_ADMIN"]
          command:
            - /topols-node
          ports:
            - containerPort: 9808
              name: healthz
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            failureThreshold: 3
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 60
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: node-plugin-dir
              mountPath: /run/topols
            - name: mount-pool
              mountPath: /mnt/pool
            - name: pod-volumes-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: "Bidirectional"
            - name: csi-plugin-dir
              mountPath: /var/lib/kubelet/plugins/kubernetes.io/csi
              mountPropagation: "Bidirectional"

        - name: csi-registrar
          image: quay.io/topols/topols:latest
          command:
            - /csi-node-driver-registrar
            - "--csi-address=/run/topols/csi-topols.sock"
            - "--kubelet-registration-path=/var/lib/kubelet/plugins/topols.kvaster.com/node/csi-topols.sock"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/topols.kvaster.com /registration/topols.kvaster.com-reg.sock"]
          volumeMounts:
            - name: node-plugin-dir
              mountPath: /run/topols
            - name: registration-dir
              mountPath: /registration

        - name: liveness-probe
          image: quay.io/topols/topols:latest
          command:
            - /livenessprobe
            - "--csi-address=/run/topols/csi-topols.sock"
          volumeMounts:
            - name: node-plugin-dir
              mountPath: /run/topols

      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: node-plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/topols.kvaster.com/node
            type: DirectoryOrCreate
        - name: csi-plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/kubernetes.io/csi
            type: DirectoryOrCreate
        - name: pod-volumes-dir
          hostPath:
            path: /var/lib/kubelet/pods/
            type: DirectoryOrCreate
        - name: mount-pool
          hostPath:
            path: /mnt/pool
            type: DirectoryOrCreate
