---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: topols-system
  name: topols-scheduler
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: topols-system
  name: psp:topols-scheduler
rules:
  - apiGroups: ["policy"]
    resources: ["podsecuritypolicies"]
    verbs: ["use"]
    resourceNames: ["topols-scheduler"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: topols-system
  name: topols-scheduler:psp:topols-scheduler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:topols-scheduler
subjects:
- kind: ServiceAccount
  namespace: topols-system
  name: topols-scheduler
