apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: topols-system
  name: topols-scheduler
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: topols-scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: topols-scheduler
    spec:
      securityContext:
        runAsUser:  10000
        runAsGroup: 10000
      serviceAccountName: topols-scheduler
      containers:
        - name: topols-scheduler
          image: quay.io/topols/topols:latest
          command:
            - /topols-scheduler
            - --config=/etc/topols/scheduler-options.yaml
          livenessProbe:
            httpGet:
              port: 9251
              path: /status
          volumeMounts:
            - mountPath: /etc/topols
              name: scheduler-options
      volumes:
        - name: scheduler-options
          configMap:
            name: scheduler-options
---
apiVersion: v1
kind: Service
metadata:
  namespace: topols-system
  name: topols-scheduler
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: topols-scheduler
  ports:
    - protocol: TCP
      port: 9251
